"""
Runtime signal handling for RetroTUI.

Installs handlers for SIGINT, SIGTSTP, SIGTERM, SIGHUP, and SIGBREAK so
that terminal signals are queued as in-app key events rather than
terminating the session.
"""

import logging
import signal
import threading

LOGGER = logging.getLogger(__name__)


def install_runtime_signal_handlers(app):
    """Install runtime signal handlers (main thread only).

    Registers the app's own bound methods (``_handle_sigint``,
    ``_handle_sigtstp``, ``_handle_shutdown_signal``) so that tests
    can inspect ``handler.__self__``.
    """
    if getattr(app, '_sigint_handler_installed', False):
        return
    if threading.current_thread() is not threading.main_thread():
        return

    planned = []
    sigint = getattr(signal, "SIGINT", None)
    if sigint is not None:
        planned.append((sigint, app._handle_sigint))
    sigbreak = getattr(signal, "SIGBREAK", None)
    if sigbreak is not None:
        planned.append((sigbreak, app._handle_sigint))
    sigtstp = getattr(signal, "SIGTSTP", None)
    if sigtstp is not None:
        planned.append((sigtstp, app._handle_sigtstp))
    for name in ("SIGTERM", "SIGHUP"):
        sig = getattr(signal, name, None)
        if sig is not None:
            planned.append((sig, app._handle_shutdown_signal))

    prev_handlers = {}
    for sig, handler in planned:
        try:
            previous = signal.getsignal(sig)
            signal.signal(sig, handler)
            prev_handlers[sig] = previous
        except (AttributeError, ValueError, OSError):
            continue

    app._prev_signal_handlers = prev_handlers
    app._prev_sigint_handler = prev_handlers.get(sigint)
    app._sigint_handler_installed = bool(prev_handlers)


def restore_runtime_signal_handlers(app):
    """Restore process signal handlers changed for runtime."""
    if not getattr(app, '_sigint_handler_installed', False):
        return
    prev_handlers = dict(getattr(app, "_prev_signal_handlers", {}) or {})
    sigint = getattr(signal, "SIGINT", None)
    if sigint is not None and sigint not in prev_handlers:
        prev = getattr(app, "_prev_sigint_handler", None)
        if prev is not None:
            prev_handlers[sigint] = prev

    for sig, prev in prev_handlers.items():
        if prev is None:
            continue
        try:
            signal.signal(sig, prev)
        except (AttributeError, ValueError, OSError):
            continue

    app._prev_signal_handlers = {}
    app._prev_sigint_handler = None
    app._sigint_handler_installed = False
    app._shutdown_signal = None


def _handle_sigint(app):
    """Queue SIGINT as in-app Ctrl+C key instead of terminating session."""
    queue_pending_signal_key(app, '\x03')


def _handle_sigtstp(app):
    """Queue SIGTSTP as in-app Ctrl+Z key instead of suspending session."""
    queue_pending_signal_key(app, '\x1a')


def _handle_shutdown_signal(app, signum):
    """Request a clean shutdown on external termination signals."""
    app._shutdown_signal = signum
    app.running = False


def queue_pending_signal_key(app, key):
    """Queue one pending control key generated by runtime signal handlers."""
    if not isinstance(key, str) or len(key) != 1:
        return
    from collections import deque
    queue = getattr(app, "_pending_signal_keys", None)
    if not isinstance(queue, deque):
        # Tolerate plain lists for backwards compatibility (tests seed the
        # attribute directly with a list) but store a deque so
        # ``popleft``/``append`` are O(1).
        app._pending_signal_keys = deque(queue or ())
        queue = app._pending_signal_keys
    queue.append(key)
    if key == '\x03':
        app._pending_sigint = True


def consume_pending_signal_key(app):
    """Return next queued control key generated by signal handlers."""
    from collections import deque
    queue = getattr(app, "_pending_signal_keys", None)
    # The queue may be a list (legacy / test fixtures) or a deque
    # (preferred for O(1) popleft). Normalise to a deque and check.
    if isinstance(queue, list):
        new_q = deque(queue)
        app._pending_signal_keys = new_q
        queue = new_q
    if isinstance(queue, deque) and queue:
        key = queue.popleft()
        app._pending_sigint = '\x03' in queue
        return key
    if getattr(app, "_pending_sigint", False):
        app._pending_sigint = False
        return '\x03'
    return None


def consume_pending_sigint(app):
    """Compatibility wrapper: return queued Ctrl+C key when available."""
    queue = getattr(app, "_pending_signal_keys", None)
    if isinstance(queue, list):
        try:
            idx = queue.index('\x03')
        except ValueError:
            idx = -1
        if idx >= 0:
            queue.pop(idx)
            app._pending_sigint = '\x03' in queue
            return '\x03'
    if getattr(app, "_pending_sigint", False):
        app._pending_sigint = False
        return '\x03'
    return None
